### ISSUE TITLE
インストール後のサーバー初回起動時にeula.txtの生成に失敗する

### ISSUE THREAD

**Issue by nozz-mat** [Server-Starter-for-Minecraft/ServerStarter2#113]
# 概要

インストール後のサーバー初回起動時にeula.txtの生成に失敗して起動できませんでした
一度eula.txtの生成に失敗した後に起動すると正常に起動しeulaへの同意を求められます

# 起動構成

- システムバージョン：2.1.2

- Ubuntu 22.04.3 LTS

- 1.20.4 (バニラ)

# 補足説明（スクリーンショットやログなど）

**Comment by nozz-mat** [comment]
この問題ですが、macのビルド版でTestDataCollectionのno_eulaを実行した際に再現しました

**Comment by CivilTT** [comment]
#202 の[`version.ts`](https://github.com/Server-Starter-for-Minecraft/ServerStarter2/blob/586921c9c8ee034cb9ae0da3d1fed35efcbf325b/src-electron/v2/source/version/version.ts#L142-L151)にて対応済みのため終了
