### ISSUE TITLE
ワールドフォルダ関連の処理を修正

### ISSUE THREAD

**Issue by CivilTT** [Server-Starter-for-Minecraft/ServerStarter2#142]
# 概要

ワールドフォルダ関連の機能について，不自然な挙動やバグが発生しているため，これらを修正する必要がある

- ワールドフォルダの非表示ボタンが選択中のワールドフォルダに対しても押下できてしまう問題の修正
- システム起動時に読み込み対象のワールドフォルダにワールドがない場合，またはすべてのワールドがエラーの時に，新規ワールドの生成が実行されない問題の修正
- ワールドフォルダを追加したときに，当該フォルダに格納されているワールド一覧を読み込むことができない問題の修正（ワールドフォルダ追加時に`API.GetWorldAbbr()`を実行する）

# 起動構成

- システムバージョン：2.1.2

## 追加機能要望
- ワールド一覧の中に保存場所の仕切りを追加（Miniでは仕切り線のみ，Fullでは折り畳みバーと保存場所名を表示）
- デフォルトの保存先を指定するピン機能
- 順番変更機能の追加（順番によって表示の優先順位を変更）

**Comment by txkodo** [comment]
解決済みか要確認
