### ISSUE TITLE
プラグインまたMOD

### ISSUE THREAD

**Issue by appipinopi** [Server-Starter-for-Minecraft/ServerStarter2#195]
# 概要　プラグインまたはMOD

プラグインサーバーを選択すると入れたいと思うプラグインをワンクリックでいられるようにしてほしい。MODも同じように

GB　MB　TBの自動計算

**Comment by CivilTT** [comment]
ご意見頂戴しまして，誠にありがとうございます！

プラグインサーバーやMODサーバーはサーバーとしてのデータを保持しているものであり，「追加コンテンツ」タブを選択することで，それらサーバーにプラグインやMODを入れることができるようになっております．
サーバーと追加コンテンツをセットで保存するような機能は想定しておりませんので，ご容赦下さいませ．

また，メモリサイズの単位変換についてはサポートを予定しておりませんので，インターネット上にある変換サイト等をご参照してご入力ください！
（一般的にはメモリサイズは2GB～4GB程度に設定しておくと良いかと思われます！）
