### ISSUE TITLE
エラーコード

### ISSUE THREAD

**Issue by appipinopi** [Server-Starter-for-Minecraft/ServerStarter2#201]
# red

<エラーコードを赤色にしてほしいです>

**Comment by CivilTT** [comment]
ご意見頂戴しまして，誠にありがとうございます！
現状のServerStarter2ではエラーを赤字で表示する仕様としておりますが，システム上検知が難しいサーバーも一定数存在することから，すべてのエラーを赤字表記することはできておりません．
申し訳ありませんが，ご容赦下さいますと幸いです！
