### ISSUE TITLE
サーバーの起動に失敗した際に，サーバーログを確認できるようにする

### ISSUE THREAD

**Issue by CivilTT** [Server-Starter-for-Minecraft/ServerStarter2#62]
# 概要
サーバーが異常終了したり，前回のログを確認したい場合に簡単にログを見ることができる機能を追加したい

前回ログデータをどこかに持っておき，それを呼び出すことで再度ログを画面に表示することを想定する

ログの中でエラー部分が判明している場合は，当該箇所の色を変えるなどして強調した表現にしても良い

### システム構成案
- システム起動時にログを読み込めるようにしておき，API呼び出しがかかった際に最新のログファイルの内容を返すようにする？
- 一度サーバーを起動した際には，ログをスタックしておき，API呼び出しの際にはスタックした一覧を返すだけにすることで，ログファイルを見に行かずとも値を返せるようにする？

**Comment by txkodo** [comment]
システム構成案にある内容はバックエンドで対応

API.invokeFetchLatestLog(WorldID) を作成しフロントから発火する構成で行きたいと思います。
