### ISSUE TITLE
MohistMCが起動できない

### ISSUE THREAD

**Issue by nozz-mat** [Server-Starter-for-Minecraft/ServerStarter2#78]
# 概要
MohistMC/1.12.1が起動できませんでした。

ワールド作成→サーバーの種類をMohistMCに変更→起動
とするとコンソールでエラーを表示して落ちます。
システム側でエラーは表示されませんでした。
リリース版/開発版ともに再現しました。
一度起動できなかった後、そのまま再度起動を試みると起動できます。

# 起動構成

- システムバージョン：2.0.0
- ブランチAutoPortMappingのテストの際に発見、リリース版でも再現しました。

- MacOS

- MohistMC/1.12.1

# 補足説明（スクリーンショットやログなど）

再現手順を踏んだ際のログを添付しています。
[2024-01-04-16-2.log](https://github.com/CivilTT/ServerStarter2/files/13827351/2024-01-04-16-2.log)

## 再現手順

ワールド作成→サーバーの種類をMohistMCに変更→起動

**Comment by nozz-mat** [comment]
追加で1.18.2まで検証したところ同様の落ち方をしました

**Comment by txkodo** [comment]
以下の環境で検証しました

- ServerStarter 2.1.0 開発版
- Windows 11

MohistMC/1.12.1 は 正常に起動

MohistMC/1.18.2 は ビルド137でtol関係のエラーを吐き、ビルド136で正常に起動しました

**Comment by CivilTT** [comment]
#202 で対応済みのため終了
