### ISSUE TITLE
Zipから配布ワールドを導入する際、導入中の画面が消えない

### ISSUE THREAD

**Issue by txkodo** [Server-Starter-for-Minecraft/ServerStarter2#99]
# 概要
Zipから配布ワールドを導入する際、導入中の画面が消えない

# 起動構成

- システムバージョン：2.0.0

- Windows (22H2)

- 1.0.0 (バニラ)

# 補足説明（スクリーンショットやログなど）

## 再現手順
ワールドを追加 > 既存ワールドの導入 > ZIPファイルを選択
導入中の画面で固まることがある ( 固まらないこともある )

**Comment by CivilTT** [comment]
#139 で類似のエラーを修正済みのためClose
